name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  go_router: ^17.3.0
  fixtures:
    path: ../packages/features/fixtures
  explore:
    path: ../packages/features/explore
  live:
    path: ../packages/features/live
  my_bets:
    path: ../packages/features/my_bets
  games:
    path: ../packages/features/games
  shared_ui:
    path: ../packages/shared_ui
  styles:
    path: ../packages/styles
  rive: ^0.14.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true


  fonts:
    - family: Betclic
      fonts:
        - asset: assets/fonts/Betclic-BoldItalic.ttf
          weight: 700

        - asset: assets/fonts/Betclic-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-ExtraBoldItalic.ttf
          weight: 700

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
