name: Flutter CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  flutter_test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: |
          for test_dir in $(find . -type d -name test); do
            if find "$test_dir" -type f -name "*_test.dart" | grep -q .; then
              package_dir=$(dirname "$test_dir")
              echo "Running tests in $package_dir"

              cd "$package_dir"
              flutter test
              cd -
            fi
          done